# Task Configuration
title: RxJS Streams
position: 2
category: 'Signal Store'
preparation: false
estimated_time_in_minutes: 15
always_unlocked: false

# Git Integration
git_tag_completed: solve--signal-store-rxjs-streams
